name: Scripture Forge CC Checker Test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test tests/login/sf_cc_user.spec.ts --project=chrome-cc-checker
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        PLAYWRIGHT_ROLE: cc_checker
        SF_CC_CHECKER_EMAIL: ${{ secrets.SF_CC_CHECKER_EMAIL }}
        SF_CC_CHECKER_PASSWORD: ${{ secrets.SF_CC_CHECKER_PASSWORD }}
    - name: Generate Allure report
      if: ${{ !cancelled() }}
      run: npm run allure:generate
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-and-allure-reports
        path: |
          reports/playwright-report/
          reports/allure-results/
          reports/allure-report/
        retention-days: 30
